
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: emanzaki/fortstak:latest
        imagePullSecrets:
        - name: docker-registry-secret
        ports:
        - containerPort: 4000