apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: emanzaki/fortstak:latest
          ports:
            - containerPort: 4000
      imagePullSecrets:
        - name: docker-registry-secret
