apiVersion: argops.io/v1alpha1
kind: Application
metadata:
  name: my-app-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/emanzaki/FortStak.git'
    targetRevision: HEAD
    path: k8s/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-app-namespace

  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    
