- name: Install Apache
  yum:
    name: httpd
    state: present
    update_cache: true

- name: Get minikube IP
  command: minikube ip
  become: false
  register: minikube_ip

- name: Set minikube IP fact
  set_fact:
    minikube_ip_value: "{{ minikube_ip.stdout }}"

- name: Configure Apache reverse proxy with Minikube IP
  template:
    src: templates/minikube-proxy.j2
    dest: /etc/httpd/conf.d/minikube-proxy.conf

- name: Restart and enable Apache
  service:
    name: httpd
    state: restarted
    enabled: true
