
- name: Install Apache
  yum:
    name: httpd
    state: present
    update_cache: true

- name: Configure Reverse Proxy
  copy:
    dest: /etc/httpd/conf.d/reverse-proxy.conf
    content: |
      <VirtualHost *:80>
        ServerAdmin webmaster@localhost

        ProxyPreserveHost On
        ProxyPass / http://localhost:30080/
        ProxyPassReverse / http://localhost:30080/

        ErrorLog /var/log/httpd/error.log
        CustomLog /var/log/httpd/access.log combined
      </VirtualHost>

- name: Enable and start Apache
  service:
    name: httpd
    state: restarted
    enabled: true
