
- name: Update all packages
  package:
    name: '*'
    state: latest
    update_cache: yes

- name: Install required packages
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present


- name: Install Docker 
  package:
    name: docker
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Check if ec2-user is in docker group
  command: id ec2-user
  register: user_groups

- name: Debug groups
  debug:
    var: user_groups.stdout

