- name: Install required dependencies
  package:
    name: conntrack
    state: present
  changed_when: false

- name: Check if Minikube is already installed
  command: minikube version
  register: minikube_version
  ignore_errors: yes

- name: Download Minikube binary if not installed
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
    owner: root
    group: root
  when: minikube_version.rc != 0

- name: Check if Minikube is running
  command: minikube status
  register: minikube_status
  ignore_errors: yes
  changed_when: false

- name: Start Minikube with Docker driver if not running
  shell: |
    newgrp docker <<EONG
    minikube start --driver=docker
    EONG
  environment:
    CHANGE_MINIKUBE_NONE_USER: "true"
  become: no
  register: minikube_start
  ignore_errors: yes
  when: minikube_status.rc != 0
  until: minikube_start.rc == 0
  retries: 6         
  delay: 10

