
- name: Create Namespace for Docker registry secret
  command: minikubekubectl create namespace docker-registry-secret || true
- name: Create Docker secret for Kubernetes
  command:
    cmd: >
      minikube kubectl create secret docker-registry docker-registry-secret
      --docker-server={{ docker_registry_url }}
      --docker-username={{ docker_username }}
      --docker-password={{ docker_password }}
      --docker-email={{ docker_email }}
