- name: Check if Namespace exists
  become: no
  command: minikube kubectl -- get namespace my-app-namespace
  register: namespace_check
  ignore_errors: true

- name: Create Namespace for Application
  command: minikube kubectl -- create namespace my-app-namespace
  become: no
  when: namespace_check.rc != 0

- name: Check if Docker secret exists
  become: no
  command: minikube kubectl -- get secret docker-registry-secret -n my-app-namespace
  register: docker_secret_check
  ignore_errors: true

- name: Create Docker secret for Kubernetes
  become: no
  command:
    cmd: >
      minikube kubectl create -- secret docker-registry docker-registry-secret
      --docker-server={{ docker_registry_url }}
      --docker-username={{ docker_username }}
      --docker-password={{ docker_password }}
      --docker-email={{ docker_email }}
      -n my-app-namespace
  when: docker_secret_check.rc != 0

