---
- name: Deploy ArgoCD on Minikube
  hosts: all
  become: true
  tasks:
    - name: Database as container
      command: docker run -d -p 27017:27017 -v mongodb:/data/db --name mongodb mongo:noble
    
    - name: Check if MongoDB container is running
      shell: docker inspect -f '{{.State.Running}}' mongodb
      register: container_status
      retries: 5
      delay: 3
      until: container_status.stdout == "true"

    - name: Create DB
      command: docker exec mongodb sh -c 'mongosh --eval "use todolistDb"'
      

    - name: Ensure ArgoCD directory exists
      ansible.builtin.file:
        path: "/home/ec2-user/argocd"
        state: directory

    - name: Copy Content to ArgoCD
      ansible.builtin.copy:
        dest: "/home/ec2-user/argocd/"
        src: ../k8s/

    - name: Verify application.yml exists
      ansible.builtin.stat:
        path: "/home/ec2-user/argocd/application.yml"
      register: app_file

    - name: Create ArgoCD Application
      become: no
      command: minikube kubectl -- apply -f /home/ec2-user/argocd/application.yml
      when: app_file.stat.exists
