---
- name: Deploy ArgoCD on Minikube
  hosts: all
  become: true   
  tasks:
    - name: Ensure ArgoCD directory exists
      ansible.builtin.file:
        path: "/home/ec2-user/argocd"
        state: directory

    - name: Copy Content to ArgoCD
      ansible.builtin.copy:
        dest: "/home/ec2-user/argocd/"
        src: ../k8s/

    - name: Verify application.yml exists
      ansible.builtin.stat:
        path: "/home/ec2-user/argocd/application.yml"
      register: app_file

    - name: Create ArgoCD Application
      become: no
      command: minikube kubectl -- apply -f /home/ec2-user/argocd/application.yml
      when: app_file.stat.exists

    - name: Include Apache reverse proxy setup
      include_tasks: tasks/apache.yml
