---
- name: Setup Ec2 instance
  hosts: all
  become: true
  vars_files:
    - ./vars/docker_creds.yml
    - ./vars/git_creds.yml   
  tasks:
    - name: SetUp Docker
      include_tasks: tasks/docker.yml
    - name: SetUp Minikube
      include_tasks: tasks/minikube.yml
    - name: Add Docker credentials
      include_tasks: tasks/add-docker-cred.yml
    - name: SetUp ArgoCD
      include_tasks: tasks/argocd.yml
