name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'Todo-List-nodejs/**'
      - '.github/workflows/ci.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true  
          tags: ${{ secrets.DOCKER_USERNAME }}/fortstak:${{ github.run_number }}

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/fortstak:${{ github.run_number }}'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image (if scan passed)
        if: success()  
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fortstak:${{ github.run_number }}
